# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - GeekhubResourceBundle
    filters:
        cssrewrite: ~
        yui_css:
            jar: %kernel.root_dir%/../vendor/nervo/yuicompressor/yuicompressor.jar
        less:
            node: /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules]
            apply_to: "\.less$"
    assets:
        css_style:
            inputs:
                - %kernel.root_dir%/../src/Geekhub/ResourceBundle/Resources/public/css/base.less
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Resources/less/form.less
                - %kernel.root_dir%/../vendor/ahonymous/fontello/css/fontello.css
            filters:
                - cssrewrite
                - yui_css
            output: css/style.min.css
        javascript:
            inputs:
                - %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.10.2.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.js
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Resources/js/bc-bootstrap-collection.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/assets/js/holder.js
            output: js/scripts.min.js
