# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - GeekhubResourceBundle
    filters:
        cssrewrite: ~
        yui_css:
            jar: %kernel.root_dir%/../vendor/nervo/yuicompressor/yuicompressor.jar
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"
            formatter: "compressed"
            preserve_comments: false
        yui_js:
            jar: %kernel.root_dir%/../vendor/nervo/yuicompressor/yuicompressor.jar
    assets:
        css_style:
            inputs:
                - %kernel.root_dir%/../src/Geekhub/ResourceBundle/Resources/public/css/base.less
                - %kernel.root_dir%/../vendor/ahonymous/fontello/css/fontello.css
            filters:
                - cssrewrite
                - yui_css
            output: css/style.min.css
        javascript:
            inputs:
                - %kernel.root_dir%/../vendor/frameworks/jquery/jquery.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/assets/js/holder.js
                - %kernel.root_dir%/../src/Geekhub/DreamBundle/Resources/public/js/createDream.js
            output: js/scripts.min.js
        dream_css:
            inputs:
                - %kernel.root_dir%/../src/Geekhub/DreamBundle/Resources/public/css/jquery.tagit.css
                - %kernel.root_dir%/../src/Geekhub/DreamBundle/Resources/public/css/tagit.ui-zendesk.css
            filters:
                - cssrewrite
                - yui_css
            output: css/dream.min.css
        dream_js:
            inputs:
                - %kernel.root_dir%/../src/Geekhub/DreamBundle/Resources/public/js/jquery-ui.js
                - %kernel.root_dir%/../src/Geekhub/DreamBundle/Resources/public/js/tag-it.js
                - %kernel.root_dir%/../src/Geekhub/DreamBundle/Resources/public/js/tags.js
            output: js/dream_js.min.js
