# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - GeekhubResourceBundle
    filters:
        cssrewrite: ~
        yui_css:
            jar: %kernel.root_dir%/../vendor/nervo/yuicompressor/yuicompressor.jar
    assets:
        css_style:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap.css
                - %kernel.root_dir%/../src/Geekhub/ResourceBundle/Resources/public/css/base.css
                - %kernel.root_dir%/../vendor/ahonymous/fontello/css/fontello.css
            filters:
                - cssrewrite
                - yui_css
            output: css/style.min.css
        javascript:
            inputs:
                - %kernel.root_dir%/../vendor/frameworks/jquery/jquery.min.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.min.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/docs/assets/js/docs.min.js
            output: js/scripts.min.js
