imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: assetic.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

liip_imagine:
#    driver:               gd
#    web_root:             %kernel.root_dir%/../web
#    data_root:            %kernel.root_dir%/../web/img/blog
#    cache_mkdir_mode:     0777
#    cache_prefix:
    cache_prefix:          /upload/dream/image/cache
#    cache:                web_path
#    cache_clearer:        true
#    data_loader:          filesystem
#    controller_action:    liip_imagine.controller:filterAction
#    formats:              []
    filter_sets:
        filter1:
            quality: 60
            filters:
                relative_resize: { widen: 60 }
#                thumbnail: { size: [120, 90], mode: outbound }
        filter2:
            quality: 60
            filters:
                relative_resize: { widen: 160 }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Geekhub\AdminUserBundle\Entity\User
