_imagine:
    resource: .
    type:     imagine

geekhub_dream:
    resource: "@GeekhubDreamBundle/Resources/config/routing.yml"
    prefix:   /

geekhub_resource:
    resource: "@GeekhubResourceBundle/Resources/config/routing.yml"
    prefix:   /theme
