geekhub_user:
    resource: "@GeekhubUserBundle/Resources/config/routing.yml"
    prefix:   /

_imagine:
    resource: .
    type:     imagine

geekhub_dream:
    resource: "@GeekhubDreamBundle/Resources/config/routing.yml"
    prefix:   /
