geekhub_dream_homepage:
    pattern:  /
    defaults: { _controller: GeekhubDreamBundle:Default:index }

new_dream:
    pattern:  /dream/new
    defaults: { _controller: GeekhubDreamBundle:Dream:newDream }
