parameters:
#    geekhub_admin_user.example.class: Geekhub\AdminUserBundle\Example

services:
#    geekhub_admin_user.example:
#        class: %geekhub_admin_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
